#
<span style="font-size:40px;">**EURO/USD Currency Analysis: The pattern and volatility from 2002 to 2020.**</span>

##
<span style= "font-size:35px">**Project Goal**</span>

###
<span style="font=size:30px;">The project purpose is to examine the historical  EUR/USD exchange rate from 2002 to 2020. It explains the price patterns, seasonal trends, monthly price levels and volatility behaviours.</span>

###
<span style="font-size:40px;">**This project explores the following questions:**

###
1.What is the overall price trend of EUR/USD from 2002 to 2020? Has it appreciated or depreciated?
###
2. Which months  show the minimum and maximum average exchange rates of the year?
###
3. Which months or years experienced the highest price volatility?
###
4. What are the highest and lowest recorded prices within this period, and when did they happen?
###
5. Are there any frequent seasonal patterns in price movement?

###
Data Source: The data was sourced from the Kaggle archive via the OANDA platform, using  the eurusd_hour.csv file spanning from January 2002 to 2020.

### **Columns Available:**
* **Date:**  Date of record

* **Time:**  Hour of the day

* **BO:**  Opening price

* **BH:**  Highest price in the hour

* **BL:**  Lowest price in the hour
* **BC:**  Closing price
* **BCh:**  Bid change
* **ACh:** Ask change


### **Note:** Hourly data will be aggregated to daily averages for clearer trend analysis.

#
<span style="font-size:40px; color:orange;">**Import Libraries**</span>

In [1]:
import pandas as pd
import datetime

In [ ]:
# reading the csv file
df=pd.read_csv("eurusd_hour.csv")
df.head()

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.2852,1.2852,1.2840,1.2844,-0.0008,1.2854,1.2854,1.2842,1.2846,-0.0008
1,2005-05-02,01:00,1.2844,1.2848,1.2839,1.2842,-0.0002,1.2846,1.2850,1.2841,1.2844,-0.0002
2,2005-05-02,02:00,1.2843,1.2854,1.2841,1.2851,0.0008,1.2845,1.2856,1.2843,1.2853,0.0008
3,2005-05-02,03:00,1.2851,1.2859,1.2850,1.2851,0.0000,1.2853,1.2861,1.2852,1.2853,0.0000
4,2005-05-02,04:00,1.2852,1.2859,1.2849,1.2855,0.0003,1.2854,1.2861,1.2851,1.2857,0.0003

#
<span style="font-size:40px; color:yellow;">**Cheek the data of the table**</span>

In [4]:
#cking data wheater any null values and data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93084 entries, 0 to 93083
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    93084 non-null  object
 1   Time    93084 non-null  object
 2   BO      93084 non-null  float64
 3   BH      93084 non-null  float64
 4   BL      93084 non-null  float64
 5   BC      93084 non-null  float64
 6   BCh     93084 non-null  float64
 7   AO      93084 non-null  float64
 8   AH      93084 non-null  float64
 9   AL      93084 non-null  float64
 10  AC      93084 non-null  float64
 11  ACh     93084 non-null  float64
dtypes: float64(10), object(2)
memory usage: 8.5+ MB

In [ ]:
# Convert the DataFrame from hourly to day basis
df1=df.groupby("Date").agg({"BO":"first","BH":"max","BL":"min","BC":"last","BCh":"sum",
                        "AO":"first","AH":"max","AL":"min","AC":"last","ACh":"sum"}).reset_index()
df1.head()

,Date,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,1.28520,1.28740,1.28367,1.28540,0.00020,1.28540,1.28755,1.28387,1.28560,0.00020
1,2005-05-03,1.28550,1.29135,1.28300,1.28783,0.00223,1.28570,1.29185,1.28320,1.28798,0.00218
2,2005-05-04,1.28783,1.29733,1.28763,1.29430,0.00657,1.28798,1.29748,1.28778,1.29450,0.00662
3,2005-05-05,1.29430,1.29885,1.29263,1.29450,0.00050,1.29450,1.29900,1.29278,1.29470,0.00050
4,2005-05-06,1.29450,1.29630,1.28103,1.28140,-0.01300,1.29470,1.29645,1.28118,1.28240,-0.01220